version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todo
      MYSQL_USER: testuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    container_name: backend-container
    depends_on:
      - mysql  # ✅ MySQL이 먼저 실행된 후 backend 시작
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mysql-container:3306/todo
      - DB_USERNAME=testuser
      - DB_PASSWORD=${MYSQL_PASSWORD}
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - backend-network
    restart: unless-stopped

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx-container
    depends_on:
      - mysql
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
