version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todo
      MYSQL_USER: testuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    image: ${DOCKER_USERNAME}/todo:latest
    container_name: backend-container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:mysql://mysql-container:3306/todo
      - DB_USERNAME=testuser
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend-network
    restart: unless-stopped
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80" # Nginx의 80번 포트를 호스트의 80번 포트로 매핑
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일을 매핑
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
