version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todo
      MYSQL_USER: testuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - backend-network

  backend:
    depends_on:
      - mysql  # ✅ MySQL이 먼저 실행된 후 backend 시작
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - backend-network
    restart: on-failure
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.21.5-alpine
    depends_on:
      - mysql
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
