version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: todo
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassworD
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend_network


networks:
  backend-network:
    driver: bridge
