version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: todo
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassworD
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80" # Nginx의 80번 포트를 호스트의 80번 포트로 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일을 매핑
    networks:
      - backend_network

networks:
  backend-network:
    driver: bridge
